spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:localhost}:3306/k8s_java
    username: ${DATABASE_USER_NAME:java}
    password: ${DATABASE_USER_PASSWORD:1234}
  jpa:
    hibernate:
      # dont do this in production!!
      ddl-auto: update
  lifecycle:
    timeout-per-shutdown-phase: 30s
info:
  app:
    name: java-kubernetes
    description: Demo Kubernetes for Java Developers
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
  health:
    probes:
      enabled: true
server:
  shutdown: graceful
  servlet:
    context-path: /app
